### ISSUE TITLE
[volspotconnect2] Playback stops after the song is end

### ISSUE THREAD

**Issue by lednicazar** [balbuze/volumio-plugins#146]
I have Volumio 2.368 + the last version of volspotconnect2 installed via ssh (also tried with the one in the complements of volumio, and the issue that i'm having is if I start a song in spotify, sounds right, but after the song ends is stopped and not starting the next song (in normal spotify in pc is working), also is stopped in the mobile or pc interface.
Even if I press next in the pc app the song sometimes starts & sometimes not. Did you suffer this?

**Comment by balbuze** [comment]
This behaviour shouldn't appears with the Dev version installed via ssh. I'm using it and no such problem. but it occurs with official version. Should be fixed soon.

**Comment by lednicazar** [comment]
I format the SD, re-install volumio, first of all install by ssh the volspotconnect2 from the link & configure (version in the gui shows 0.6.6) 
... Now works....
Can be that due to install first the one from volumio some data is corrupt??

Later on to update? remove the folder & repeat the stuff via ssh?

Thanks! Great plugin!

**Comment by balbuze** [comment]
In fact,some very last changes in the official plugin brings this problem...

**Comment by kerwingroot** [comment]
I've installed a fresh volumio, installed the plugin trough volumio plugin page and the problem popped up. Removed it and installed the latest trough SSH, still hangs after each song.

**Comment by mredone** [comment]
I have the same issue, but after install via ssh it hangs after 2seconds of new song.

**Comment by lednicazar** [comment]
Yes! Usually that happend, as balbuze said. What I did:
1- Install fresh volumio -> NOT INSTALL THE PLUGING WITH THE VOLUMIO MENU
2- Activate ssh (DEV webpage)
3- Install the pluging from this github
Try!

**Comment by mredone** [comment]
I do this and the same issue. 
But. 
I use 2 rpi with 2 volumio.
On first Kitchen Volumio i use RPI0W with PCM5102 I2S and i have lastest volumio and volspotconnect2 plugin and everything work like a charm.
Second volumio is a main streamer wit rpi3 and xmos usb to i2s and es9028Q2M DAC. Latest volumio and volspotconnect2 via ssh or via plugin. And here i have issue with stop after track change.

Maybe is a alsa problem or driver problem?

**Comment by kerwingroot** [comment]
I have a RPI2 with I2S (Hifiberry Digi+) and have this problem, so shouldn't be ALSA/Driver right?

**Comment by nat80** [comment]
I have the same issue with last version of volspotconnect2 installed via ssh, spotify stop playing the playlist after each track played :/
With the volspotconnect plugin it works well but I can't control the volume via Spotify

**Comment by ashthespy** [comment]
@nat80 can you confirm if you are truly on the dev version by:

1. Uninstall the plugin via the UI
2. ssh into Volumio and confirm that `/data/plugins/music_service/volspotconnect2/` doesn't exist 
3. Install latest repo version?

**Comment by nat80** [comment]
@ashthespy 
I did what you told me, I have uninstalled the plugin and volspotconnect2 didn't exist in /music_service and I don't know why but now it works perfectly even after reboot ! I hope it's not temporary :)
Yet before I had installed the latest version a few hours ago (or I thought)
Thank you !

**Comment by ashthespy** [comment]
@nat80 It works, cause you were still on the old (official) version, the current plugin install method via the pluginhelper is quite roundabout, but I guess there is a reason for everything ;-)
We should probably update the Readme to mention it's better to uninstall the plugin first via the UI.

**Comment by egon99** [comment]
I had the same issue, on both my Volumio players (RPI2 and RPI3). In both cases, the issue was solved by re-installing Volumio  2.368 and installing the plugin via SSH.

**Comment by WalterBorgstein** [comment]
What would be the correct wget url to get the latetst dev version?
By using wget https://github.com/balbuze/volumio-plugins/raw/master/plugins/music_service/volspotconnect2/volspotconnect2.zip
i still have the "next song not played issue".

I couldnt find a clear "dev" branch in GIT. Help or a hint is appreciated ;)

**Comment by ashthespy** [comment]
@WalterBorgstein please uninstall the version from the plugin manager first ( full steps https://github.com/balbuze/volumio-plugins/issues/146#issuecomment-373209730)

**Comment by WalterBorgstein** [comment]
I uninstalled the version using the GUI (felt unnatural to uninstall such a nice plugin ;). But since you were so sure, I redid the whole thing and rebooted after removing it.
After installing now it works! Might be some mistake of me, or the reboot did help. Thanks! And also thanks for the plugin! Really adds value to the Volumio set-up. easy to use by my family.

**Comment by ashthespy** [comment]
Glad to help Walter, the volumio plugin manager doens't seem to overwrite the files they exist already - hence the need to uninstall :-)

**Comment by kerwingroot** [comment]
What worked for me:
1. Uninstall trough Volumio Plugin page
2. Removed old files (folder remained after uninstall) trough SSH with rm -rf ./volspotconnect2
3. Installed with SSH as instructed
4. Reboot (Spotify didn't see Volumio yet)
5. Play music!

**Comment by balbuze** [comment]
solved
